const COURSE_CATEGORIES = [
  { id: "all", name: "All Courses", icon: "📚" },
  { id: "3d-printing", name: "3D Printing", icon: "🖨️" },
  { id: "business", name: "Business", icon: "💼" },
  { id: "development", name: "Development", icon: "💻" },
  { id: "investment", name: "Investment", icon: "📈" },
  { id: "design", name: "Design", icon: "🎨" },
  { id: "marketing", name: "Marketing", icon: "📣" },
];

const COURSES = [
  {
    id: "3d-printing-masterclass",
    title: "3D Printing Masterclass: From Design to Production",
    category: "3d-printing",
    price: 149,
    rating: 4.9,
    students: 2840,
    duration: "12 hours",
    level: "Beginner",
    instructor: "Sarah Chen",
    instructorRole: "Additive Manufacturing Expert",
    instructorImage: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&q=80",
    image: "https://images.unsplash.com/photo-1616400650995-63d9f2d1d2d4?w=800&q=80",
    badge: "Bestseller",
    description: "Master 3D printing from fundamentals to advanced production techniques. Learn CAD modeling, slicer settings, material selection, and post-processing for professional results.",
    modules: [
      {
        title: "Introduction to 3D Printing",
        lessons: ["What is 3D Printing?", "Types of 3D Printers", "Setting Up Your Workspace"],
      },
      {
        title: "Design & Modeling",
        lessons: ["CAD Basics with Fusion 360", "Design for Printability", "Support Structures"],
      },
      {
        title: "Printing & Post-Processing",
        lessons: ["Slicer Configuration", "Material Guide", "Finishing Techniques"],
      },
    ],
  },
  {
    id: "business-strategy",
    title: "Business Strategy & Leadership Fundamentals",
    category: "business",
    price: 199,
    rating: 4.8,
    students: 5120,
    duration: "18 hours",
    level: "Intermediate",
    instructor: "James Mitchell",
    instructorRole: "Business Consultant",
    instructorImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
    image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80",
    badge: "Popular",
    description: "Build strategic thinking skills to grow your business. Cover market analysis, competitive positioning, team leadership, and scalable business models.",
    modules: [
      {
        title: "Strategic Foundations",
        lessons: ["Vision & Mission", "SWOT Analysis", "Market Research"],
      },
      {
        title: "Leadership Skills",
        lessons: ["Team Building", "Decision Making", "Conflict Resolution"],
      },
      {
        title: "Growth Strategies",
        lessons: ["Scaling Operations", "Partnerships", "Exit Planning"],
      },
    ],
  },
  {
    id: "fullstack-development",
    title: "Full-Stack Web Development Bootcamp",
    category: "development",
    price: 299,
    rating: 4.9,
    students: 8920,
    duration: "45 hours",
    level: "Beginner",
    instructor: "Alex Rivera",
    instructorRole: "Senior Software Engineer",
    instructorImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80",
    badge: "Bestseller",
    description: "Become a full-stack developer with HTML, CSS, JavaScript, React, Node.js, and databases. Build real-world projects and deploy to production.",
    modules: [
      {
        title: "Frontend Fundamentals",
        lessons: ["HTML & CSS", "JavaScript ES6+", "React Basics"],
      },
      {
        title: "Backend Development",
        lessons: ["Node.js & Express", "REST APIs", "Database Design"],
      },
      {
        title: "Deployment & DevOps",
        lessons: ["Git & GitHub", "Cloud Deployment", "CI/CD Basics"],
      },
    ],
  },
  {
    id: "investment-fundamentals",
    title: "Investment Fundamentals: Stocks, Bonds & Portfolio",
    category: "investment",
    price: 179,
    rating: 4.7,
    students: 6340,
    duration: "15 hours",
    level: "Beginner",
    instructor: "Emily Watson",
    instructorRole: "CFA, Portfolio Manager",
    instructorImage: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&q=80",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    badge: "New",
    description: "Learn to invest wisely with proven strategies. Understand stocks, bonds, ETFs, portfolio diversification, and long-term wealth building.",
    modules: [
      {
        title: "Investment Basics",
        lessons: ["Risk & Return", "Asset Classes", "Market Mechanics"],
      },
      {
        title: "Portfolio Building",
        lessons: ["Diversification", "Asset Allocation", "Rebalancing"],
      },
      {
        title: "Advanced Topics",
        lessons: ["Tax-Efficient Investing", "Retirement Planning", "Behavioral Finance"],
      },
    ],
  },
  {
    id: "python-data-science",
    title: "Python for Data Science & Machine Learning",
    category: "development",
    price: 249,
    rating: 4.8,
    students: 7210,
    duration: "32 hours",
    level: "Intermediate",
    instructor: "David Kim",
    instructorRole: "Data Scientist",
    instructorImage: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&q=80",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    badge: "Popular",
    description: "Master Python, pandas, NumPy, and scikit-learn. Build machine learning models and analyze data for business insights.",
    modules: [
      {
        title: "Python Foundations",
        lessons: ["Python Syntax", "Data Structures", "Functions & OOP"],
      },
      {
        title: "Data Analysis",
        lessons: ["Pandas & NumPy", "Data Visualization", "Statistical Analysis"],
      },
      {
        title: "Machine Learning",
        lessons: ["Supervised Learning", "Unsupervised Learning", "Model Evaluation"],
      },
    ],
  },
  {
    id: "digital-marketing",
    title: "Digital Marketing Mastery: SEO, Ads & Social",
    category: "marketing",
    price: 159,
    rating: 4.6,
    students: 4580,
    duration: "20 hours",
    level: "Beginner",
    instructor: "Lisa Park",
    instructorRole: "Marketing Director",
    instructorImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    badge: null,
    description: "Grow your brand online with SEO, Google Ads, social media marketing, email campaigns, and analytics-driven strategies.",
    modules: [
      {
        title: "Marketing Foundations",
        lessons: ["Digital Landscape", "Customer Personas", "Content Strategy"],
      },
      {
        title: "Channels & Tactics",
        lessons: ["SEO Fundamentals", "Paid Advertising", "Social Media"],
      },
      {
        title: "Analytics & Optimization",
        lessons: ["Google Analytics", "A/B Testing", "ROI Measurement"],
      },
    ],
  },
  {
    id: "ui-ux-design",
    title: "UI/UX Design: Create Beautiful User Experiences",
    category: "design",
    price: 189,
    rating: 4.8,
    students: 3890,
    duration: "22 hours",
    level: "Beginner",
    instructor: "Maria Santos",
    instructorRole: "Lead Product Designer",
    instructorImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80",
    badge: "Popular",
    description: "Learn user research, wireframing, prototyping, and visual design. Create portfolio-ready projects with Figma.",
    modules: [
      {
        title: "UX Research",
        lessons: ["User Interviews", "Personas & Journey Maps", "Usability Testing"],
      },
      {
        title: "Design Process",
        lessons: ["Wireframing", "Prototyping in Figma", "Design Systems"],
      },
      {
        title: "Visual Design",
        lessons: ["Typography & Color", "Layout Principles", "Portfolio Project"],
      },
    ],
  },
  {
    id: "entrepreneurship",
    title: "Startup Entrepreneurship: Launch Your Business",
    category: "business",
    price: 219,
    rating: 4.7,
    students: 3210,
    duration: "16 hours",
    level: "All Levels",
    instructor: "Tom Oliver",
    instructorRole: "Serial Entrepreneur",
    instructorImage: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=80",
    image: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&q=80",
    badge: null,
    description: "From idea to launch — validate your concept, build an MVP, find funding, and scale your startup with proven frameworks.",
    modules: [
      {
        title: "Idea Validation",
        lessons: ["Problem-Solution Fit", "Market Sizing", "Customer Discovery"],
      },
      {
        title: "Building Your MVP",
        lessons: ["Lean Startup", "Product Development", "Launch Strategy"],
      },
      {
        title: "Funding & Growth",
        lessons: ["Pitch Deck", "Investor Relations", "Scaling Tactics"],
      },
    ],
  },
  {
    id: "crypto-investing",
    title: "Cryptocurrency & Blockchain Investing",
    category: "investment",
    price: 169,
    rating: 4.5,
    students: 5670,
    duration: "10 hours",
    level: "Intermediate",
    instructor: "Ryan Brooks",
    instructorRole: "Blockchain Analyst",
    instructorImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80",
    badge: "New",
    description: "Understand blockchain technology, evaluate crypto assets, manage risk, and build a diversified digital asset portfolio.",
    modules: [
      {
        title: "Blockchain Basics",
        lessons: ["How Blockchain Works", "Bitcoin & Ethereum", "DeFi Overview"],
      },
      {
        title: "Crypto Investing",
        lessons: ["Token Analysis", "Wallet Security", "Trading Strategies"],
      },
      {
        title: "Risk Management",
        lessons: ["Portfolio Allocation", "Tax Considerations", "Future Trends"],
      },
    ],
  },
];

const INSTRUCTORS = [
  { name: "Tom Oliver", role: "Founder & CEO", image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=80" },
  { name: "Sarah Chen", role: "Lead Instructor", image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&q=80" },
  { name: "James Mitchell", role: "Business Coach", image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80" },
  { name: "Emily Watson", role: "Investment Expert", image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&q=80" },
  { name: "Alex Rivera", role: "Tech Lead", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" },
  { name: "Lisa Park", role: "Marketing Head", image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80" },
  { name: "David Kim", role: "Data Scientist", image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&q=80" },
];

const PLATFORM_STATS = {
  students: "50k+",
  completionRate: "92%",
  coursesSold: "120k+",
  satisfiedLearners: "48k+",
};
